---
Layout: Default
author_profile: true
toc: true
toc_sticky: true

categories:
    - python_basic
tags: [Python, 기초]
---

# 구문오류와 예외
## 오류의 종류
- 프로그램 실행 전 발생 오류 - syntax error(문법 자체가 틀린 경우)
- 프로그램 실행 중 발생 오류 - Runtime error 또는 예외(Exeption)  

예외의 예) Index error, time error,  value error  
예측하지 못한 에러를 피하는 방법: 예외처리(Exeption Handling)

## 예외를 처리하는 방법 : 
1. Try Except 키워드 구문
2. if 조건식을 통한 필터링

        ```python
        x = input("정수 입력")
        if x.isdigit():
            x_num = int(x)
            ...
        ```

## try-except 
try 안 실행문을 실행 중 오류 발생 시 except 예외 처리문이 실행된다.

```python
try:
    실행문
except:
    예외 처리문
```

```python
list_input_a = ["52", "273", "32", "스파이", "103"]

list_number = []

# try 예외 처리문을 사용하면 for문에 문제가 발생하더라도 중단되지 않고 모두 실행할 수 있다.
for item in list_input_a:
    try:
        float(item)
        list_number.append(item)
    except:
        pass

print("{} 내부에 있는 숫자는".format(list_input_a))
print("{}입니다.".format(list_number))
```

런타임 오류에 대비하기 위해 모든 코드를 try 문으로 감싸줘도 되겠지만,  
오류 발생 지점을 찾고 디버깅 하기 위해서는 구간마다 try문을 분리해서 작성합니다.

## try-except-else
else 구문은 try에서 오류가 발생하지 않았을 때 실행된다.

```
try:
    예외 발생 가능성이 있는 코드
except:
    예외가 발생했을 때 실행되는 코드
else:
    예외가 발생되지 않았을 때 실행되는 코드
```

<br>

올바른 입력을 받기 위한 예외 처리문

```python
while True:
    try:
        number_input = int(input("정수입력> "))
    except:
        print("정수를 입력하지 않았습니다.")
    else:
        print("원의 반지름: ", number_input)
        print("원의 둘레: ", 2 * 3.14 * number_input)
        print("원의 넓이: ", 3.14 * number_input * number_input)
```

## finally 
예외 여부 상관 없이 실행되는 구문입니다.

```
try:
    예외 발생 가능성이 있는 코드
except:
    예외가 발생했을 때 실행되는 코드
else:
    예외가 발생되지 않았을 때 실행되는 코드
finally:
    무조건 실행할 코드
```

```python
try:
    file = open("info.txt", "w")
    # 파일 처리 수행
    # ~~~

    file.close()
except:
    print("오류가 발생했습니다.")

print("# 파일이 제대로 닫혔는지 확인하기")
print(f"{file.closed=}")

```
<br>

특정 예외만 받기

```python
try:
    file = open("test.txt", "r")
    file.close()

# Exception은 예외 객체이며, except 구문 뒤에 어떤 예외를 받을 것인지 작성할 수 있다.
# as 키워드로 별명을 설정한다.
except Exception as e:
    print("에러발생", e)
```